### PR TITLE
chore: added user-dashboard page

### LINKED ISSUE #3: User Dashboard Ui
1. Create a user dashboard to let user upload the video
2. Take care of the whole UI/UX
3. Let user see his history on the page

### PR DESCRIPTION
**Pull request by y4sh1k4**
Fix #3

### CODE REVIEW

**Comment by y4sh1k4** [comment]
Fix #5

**Review by kelvinpraises — CHANGES_REQUESTED** [review]
@y4sh1k4 I believe there is an error

`Type error: Object literal may only specify known properties, and 'totalWords' does not exist in type '(prevState: null) => null'.`

Please run `npm run build` offline to see the full error.

**Comment by y4sh1k4** [comment]
Fix #6

**Comment by y4sh1k4** [comment]
Fix #4

**Review by kelvinpraises — APPROVED** [review]

**Pull request merged**
